###
POST http://localhost:3000/dashboard/user HTTP:/1.1
Content-Type: application/json
{
    "name":"student 1",
    "lastname":"lastname 1"
    "age":22,
    "email":"student@ucaldas.edu.co"
}

###
GET http://localhost:3000/dashboard/users HTTP:/1.1
###
DELETE  http://localhost:3000/dashboard/users/id HTTP:/1.1
###
PUT http://localhost:3000/dashboard/users/id HTTP:/1.1
Content-Type: application/json